vim.api.nvim_command("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.api.nvim_command("syntax reset")
end
vim.g.colors_name = "molokai"
local highlights = {
	-- Treesitter breaking changes
	{ "@module", "Identifier" },
	{ "@markup", "@text" },
	{ "@markup.heading", "Title" },
	{ "@markup.raw", "Comment" },
	{ "@markup.link", "Identifier" },
	{ "@markup.link.url", "Underlined" },
	{ "@markup.link.label", "SpecialChar" },
	{ "@markup.list", "Delimiter" },
	{ "@boolean", "Boolean" },
	{ "Boolean", { fg = "#AE81FF" } },
	{ "Character", { fg = "#E6DB74" } },
	{ "Number", { fg = "#AE81FF" } },
	{ "String", { fg = "#E6DB74" } },
	{ "Conditional", { fg = "#F92672", bold = true } },
	{ "Constant", { fg = "#AE81FF", bold = true } },
	{ "Cursor", { fg = "#000000", bg = "#F8F8F0" } },
	{ "iCursor", { fg = "#000000", bg = "#F8F8F0" } },
	{ "Debug", { fg = "#BCA3A3", bold = true } },
	{ "Define", { fg = "#66D9EF" } },
	{ "Delimiter", { fg = "#8F8F8F" } },
	-- diff (unified)
	{ "diffAdded", { fg = "#2BFF2B", gui = "NONE", ctermfg = 46, cterm = "NONE" } },
	{ "diffRemoved", { fg = "#FF2B2B", gui = "NONE", ctermfg = 196, cterm = "NONE" } },
	{ "diffSubname", "Normal" },
	-- diff (side-by-side)
	{ "DiffAdd", { fg = "black", bg = "#2BFF2B", ctermfg = 0, ctermbg = 46, gui = "NONE", cterm = "NONE" } },
	{ "DiffChange", { fg = "white", bg = "#4C4745", ctermfg = 255, ctermbg = 239, gui = "NONE", cterm = "NONE" } },
	{ "DiffDelete", { fg = "white", bg = "#FF2B2B", ctermfg = 255, ctermbg = 196, gui = "NONE", cterm = "NONE" } },
	{ "DiffText", { fg = "#000000", bg = "#ffb733", gui = "NONE", ctermfg = 000, ctermbg = 214, cterm = "NONE" } },
	{ "Directory", { fg = "#A6E22E", bold = true } },
	{ "Error", { fg = "White", bg = "Red", ctermfg = 15, ctermbg = 9 } },
	{ "ErrorMsg", { fg = "White", bg = "Red", bold = true, ctermfg = 15, ctermbg = 1, cterm = "bold" } },
	{ "Exception", { fg = "#A6E22E", bold = true } },
	{ "Float", { fg = "#AE81FF" } },
	{ "FoldColumn", { fg = "#465457", bg = "#000000", ctermfg = 242, ctermbg = 16 } },
	{ "Folded", { fg = "#465457", bg = "NONE", ctermfg = 242, ctermbg = "NONE" } },
	{ "Function", { fg = "#A6E22E" } },
	{ "Identifier", { fg = "#FD971F" } },
	{ "Variable", { fg = "#FD971F" } },
	{ "@variable", { fg = "#FD971F" } },
	{ "LspInlayHint", { fg = "#DFCFCF" } },
	{ "Builtin", { fg = "#FFD180" } },
	{ "Ignore", { fg = "#808080", bg = "bg" } },
	{ "Keyword", { fg = "#F92672", bold = true } },
	{ "Label", { fg = "#E6DB74", gui = "none" } },
	{ "Macro", { fg = "#C4BE89", italic = true } },
	{ "SpecialKey", { fg = "#66D9EF", italic = true } },
	{ "MatchParen", { fg = "#000000", bg = "#FD971F", gui = "NONE", ctermfg = 0, ctermbg = 208, cterm = "NONE" } },
	{ "ModeMsg", { fg = "#E6DB74" } },
	{ "MoreMsg", { fg = "#E6DB74" } },
	{ "Operator", { fg = "#F92672" } },
	-- completion/popup menu
	{ "Pmenu", { fg = "white", bg = "#000000", ctermfg = 255, ctermbg = 16 } },
	{ "PmenuSel", { fg = "white", bg = "#0a9dff", gui = "NONE", ctermfg = 255, ctermbg = 242, cterm = "NONE" } },
	{ "PmenuSbar", { fg = "NONE", bg = "#857f78", ctermbg = 232 } },
	{ "PmenuThumb", { fg = "#242321", bg = "NONE", ctermfg = 81 } },
	{ "PreCondit", { fg = "#A6E22E", bold = true } },
	{ "PreProc", { fg = "#A6E22E" } },
	{ "Question", { fg = "#66D9EF" } },
	{ "Repeat", { fg = "#F92672", bold = true } },
	{ "Search", { fg = "#000000", bg = "#FFE792", ctermfg = 0, ctermbg = 222, cterm = "NONE" } },
	{ "IncSearch", { fg = "#C4BE89", bg = "#000000", ctermfg = 193, ctermbg = 16 } },
	{ "QuickFixLine", { fg = "NONE", bg = "#F92672", ctermbg = 197 } },
	-- marks
	{ "SignColumn", { fg = "#A6E22E", bg = "#232526" } },
	{ "SpecialChar", { fg = "#F92672", bold = true } },
	{ "SpecialComment", { fg = "#7E8E91", bold = true } },
	{ "Special", { fg = "#66D9EF", bg = "bg", italic = true } },
	{ "SpellBad", { sp = "#FF0000", undercurl = true, cterm = "underline" } },
	{ "SpellCap", { sp = "#7070F0", undercurl = true, cterm = "undercurl" } },
	{ "SpellLocal", { sp = "#70F0F0", undercurl = true, cterm = "underline" } },
	{ "SpellRare", { sp = "#FFFFFF", undercurl = true, cterm = "underline" } },
	{ "Statement", { fg = "#F92672", bold = true, ctermfg = 197, cterm = "bold" } },
	{ "StatusLine", { fg = "#455354", bg = "fg" } },
	{ "StatusLineNC", { fg = "#808080", bg = "#080808" } },
	{ "StorageClass", { fg = "#FD971F", italic = true } },
	{ "Structure", { fg = "#66D9EF" } },
	{ "Tag", { fg = "#F92672", italic = true } },
	{ "Title", { fg = "#ef5939" } },
	{ "Todo", { fg = "#FFFFFF", bg = "bg", bold = true } },
	{ "Typedef", { fg = "#66D9EF" } },
	{ "Type", { fg = "#66D9EF", gui = "none" } },
	{ "Underlined", { fg = "#808080", underline = true } },
	{ "VertSplit", { fg = "#808080", bg = "#080808", bold = true } },
	{ "VisualNOS", { fg = "NONE", bg = "#403D3D" } },
	{ "Visual", { fg = "NONE", bg = "#403D3D" } },
	{ "WarningMsg", { fg = "#FFFFFF", bg = "#333333", bold = true } },
	{ "WildMenu", { fg = "#66D9EF", bg = "#000000" } },
	{ "TabLineFill", { fg = "#1B1D1E", bg = "#1B1D1E" } },
	{ "TabLine", { bg = "#1B1D1E", fg = "#808080", gui = "none" } },
	{ "Normal", { fg = "#F8F8F2", bg = "#1B1D1E" } },
	{ "Comment", { fg = "#7E8E91" } },
	{ "Cursor", { fg = "#000000", bg = "#F8F8F0" } },
}
for _, highlight in ipairs(highlights) do
	local group, props = highlight[1], highlight[2]
	vim.api.nvim_set_hl(0, group, type(props) == "table" and props or { link = props })
end
