-- Define colors
local colors = {
	black = "#000000",
	white = "#FFFFFF",
	red = "#FF2B2B",
	green = "#2BFF2B",
	blue = "#66D9EF",
	purple = "#AE81FF",
	yellow = "#E6DB74",
	dark_gray = "#808080",
	light_gray = "#E6DB74",
	dark_red = "#F92672",
	dark_green = "#66D9EF",
	orange = "#FD971F",
	pink = "#F92672",
	cyan = "#70F0F0",
	dark_cyan = "#7070F0",
	lgray = "#EDEDED",
	bg = "bg",
}
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end
vim.g.colors_name = "molokai"
local highlights = {
	{ "@module", "Identifier" },
	{ "@markup", "@text" },
	{ "@markup.heading", "Title" },
	{ "@markup.raw", "Comment" },
	{ "@markup.link", "Identifier" },
	{ "@markup.link.url", "Underlined" },
	{ "@markup.link.label", "SpecialChar" },
	{ "@markup.list", "Delimiter" },
	{ "Boolean", { guifg = colors.purple } },
	{ "Character", { guifg = colors.yellow } },
	{ "Number", { guifg = colors.purple } },
	{ "String", { guifg = colors.yellow } },
	{ "Conditional", { guifg = colors.dark_red, gui = "bold" } },
	{ "Constant", { guifg = colors.purple, gui = "bold" } },
	{ "Cursor", { guifg = colors.black, guibg = colors.light_gray } },
	{ "iCursor", { guifg = colors.black, guibg = colors.light_gray } },
	{ "Debug", { guifg = colors.red, gui = "bold" } },
	{ "Define", { guifg = colors.blue } },
	{ "Delimiter", { guifg = colors.dark_gray } },
	{ "diffAdded", { guifg = colors.green, gui = "NONE", ctermfg = 46, cterm = "NONE" } },
	{ "diffRemoved", { guifg = colors.red, gui = "NONE", ctermfg = 196, cterm = "NONE" } },
	{ "diffSubname", "Normal" },
	{
		"DiffAdd",
		{ guifg = colors.black, guibg = colors.green, ctermfg = 0, ctermbg = 46, gui = "NONE", cterm = "NONE" },
	},
	{
		"DiffChange",
		{ guifg = colors.white, guibg = colors.lgray, ctermfg = 255, ctermbg = 239, gui = "NONE", cterm = "NONE" },
	},
	{
		"DiffDelete",
		{ guifg = colors.white, guibg = colors.red, ctermfg = 255, ctermbg = 196, gui = "NONE", cterm = "NONE" },
	},
	{
		"DiffText",
		{ guifg = colors.black, guibg = colors.orange, gui = "NONE", ctermfg = 000, ctermbg = 214, cterm = "NONE" },
	},
	{ "Directory", { guifg = colors.light_gray, gui = "bold" } },
	{ "Error", { guifg = colors.white, guibg = colors.red, ctermfg = 15, ctermbg = 9 } },
	{
		"ErrorMsg",
		{ guifg = colors.white, guibg = colors.red, gui = "bold", ctermfg = 15, ctermbg = 1, cterm = "bold" },
	},
	{ "Exception", { guifg = colors.light_gray, gui = "bold" } },
	{ "Float", { guifg = colors.purple } },
	{ "FoldColumn", { guifg = colors.dark_gray, guibg = colors.black, ctermfg = 242, ctermbg = 16 } },
	{ "Folded", { guifg = colors.dark_gray, guibg = "NONE", ctermfg = 242, ctermbg = "NONE" } },
	{ "Function", { guifg = colors.light_gray } },
	{ "Identifier", { guifg = colors.orange } },
	{ "Variable", { guifg = colors.orange } },
	{ "@variable", { guifg = colors.orange } },
	{ "LspInlayHint", { guifg = colors.dark_gray } },
	{ "Builtin", { guifg = colors.light_gray } },
	{ "Ignore", { guifg = colors.dark_gray, guibg = colors.bg } },
	{ "Keyword", { guifg = colors.dark_red, gui = "bold" } },
	{ "Label", { guifg = colors.yellow, gui = "none" } },
	{ "Macro", { guifg = colors.light_gray, gui = "italic" } },
	{ "SpecialKey", { guifg = colors.blue, gui = "italic" } },
	{
		"MatchParen",
		{ guifg = colors.black, guibg = colors.orange, gui = "NONE", ctermfg = 000, ctermbg = 208, cterm = "NONE" },
	},
	{ "ModeMsg", { guifg = colors.yellow } },
	{ "MoreMsg", { guifg = colors.yellow } },
	{ "Operator", { guifg = colors.dark_red } },
	{ "Pmenu", { guifg = colors.white, guibg = colors.black, ctermfg = 255, ctermbg = 16 } },
	{
		"PmenuSel",
		{ guifg = colors.white, guibg = colors.cyan, gui = "NONE", ctermfg = 255, ctermbg = 242, cterm = "NONE" },
	},
	{ "PmenuSbar", { guifg = "NONE", guibg = colors.dark_gray, ctermbg = 232 } },
	{ "PmenuThumb", { guifg = colors.dark_gray, guibg = "NONE", ctermfg = 81 } },
	{ "PreCondit", { guifg = colors.light_gray, gui = "bold" } },
	{ "PreProc", { guifg = colors.light_gray } },
	{ "Question", { guifg = colors.blue } },
	{ "Repeat", { guifg = colors.dark_red, gui = "bold" } },
	{ "Search", { guifg = colors.black, guibg = colors.orange, ctermfg = 0, ctermbg = 222, cterm = "NONE" } },
	{ "IncSearch", { guifg = colors.light_gray, guibg = colors.black, ctermfg = 193, ctermbg = 16 } },
	{ "QuickFixLine", { guifg = "NONE", guibg = colors.dark_red, ctermbg = 197 } },
	{ "SignColumn", { guifg = colors.light_gray, guibg = colors.bg } },
	{ "SpecialChar", { guifg = colors.dark_red, gui = "bold" } },
	{ "SpecialComment", { guifg = colors.dark_gray, gui = "bold" } },
	{ "Special", { guifg = colors.blue, guibg = colors.bg, gui = "italic" } },
	{ "SpellBad", { guisp = colors.red, gui = "undercurl", cterm = "underline" } },
	{ "SpellCap", { guisp = colors.cyan, gui = "undercurl", cterm = "undercurl" } },
	{ "SpellLocal", { guisp = colors.cyan, gui = "undercurl", cterm = "underline" } },
	{ "SpellRare", { guisp = colors.white, gui = "undercurl", cterm = "underline" } },
	{ "Statement", { guifg = colors.dark_red, gui = "bold", ctermfg = 197, cterm = "bold" } },
	{ "StatusLine", { guifg = colors.dark_gray, guibg = colors.bg } },
	{ "StatusLineNC", { guifg = colors.dark_gray, guibg = colors.black } },
	{ "StorageClass", { guifg = colors.orange, gui = "italic" } },
	{ "Structure", { guifg = colors.blue } },
	{ "Tag", { guifg = colors.dark_red, gui = "italic" } },
	{ "Title", { guifg = colors.light_gray } },
	{ "Todo", { guifg = colors.white, guibg = colors.bg, gui = "bold" } },
	{ "Typedef", { guifg = colors.blue } },
	{ "Type", { guifg = colors.blue, gui = "none" } },
	{ "Underlined", { guifg = colors.dark_gray, gui = "underline" } },
	{ "VertSplit", { guifg = colors.dark_gray, guibg = colors.black, gui = "bold" } },
	{ "VisualNOS", { guifg = "NONE", guibg = colors.lgray } },
	{ "Visual", { guifg = "NONE", guibg = colors.bg } },
	{ "WarningMsg", { guifg = colors.white, guibg = colors.lgray, gui = "bold" } },
	{ "WildMenu", { guifg = colors.blue, guibg = colors.black } },
	{ "TabLineFill", { guifg = colors.bg, guibg = colors.bg } },
	{ "TabLine", { guibg = colors.bg, guifg = colors.dark_gray, gui = "none" } },
	{ "Normal", { guifg = colors.light_gray, guibg = colors.bg } },
	{ "Comment", { guifg = colors.dark_gray } },
	{ "Cursor", { guifg = colors.black, guibg = colors.light_gray } },
}
for _, highlight in ipairs(highlights) do
	local group, props = highlight[1], highlight[2]
	vim.api.nvim_set_hl(0, group, props)
end
