vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end
vim.g.colors_name = "molokai"
local highlights = {
	-- Treesitter breaking changes
	{ "@module", "Identifier" },
	{ "@markup", "@text" },
	{ "@markup.heading", "Title" },
	{ "@markup.raw", "Comment" },
	{ "@markup.link", "Identifier" },
	{ "@markup.link.url", "Underlined" },
	{ "@markup.link.label", "SpecialChar" },
	{ "@markup.list", "Delimiter" },
	{ "Boolean", { guifg = "#AE81FF" } },
	{ "Character", { guifg = "#E6DB74" } },
	{ "Number", { guifg = "#AE81FF" } },
	{ "String", { guifg = "#E6DB74" } },
	{ "Conditional", { guifg = "#F92672", gui = "bold" } },
	{ "Constant", { guifg = "#AE81FF", gui = "bold" } },
	{ "Cursor", { guifg = "#000000", guibg = "#F8F8F0" } },
	{ "iCursor", { guifg = "#000000", guibg = "#F8F8F0" } },
	{ "Debug", { guifg = "#BCA3A3", gui = "bold" } },
	{ "Define", { guifg = "#66D9EF" } },
	{ "Delimiter", { guifg = "#8F8F8F" } },
	-- diff (unified)
	{ "diffAdded", { guifg = "#2BFF2B", gui = "NONE", ctermfg = 46, cterm = "NONE" } },
	{ "diffRemoved", { guifg = "#FF2B2B", gui = "NONE", ctermfg = 196, cterm = "NONE" } },
	{ "diffSubname", "Normal" },
	-- diff (side-by-side)
	{ "DiffAdd", { guifg = "black", guibg = "#2BFF2B", ctermfg = 0, ctermbg = 46, gui = "NONE", cterm = "NONE" } },
	{
		"DiffChange",
		{ guifg = "white", guibg = "#4C4745", ctermfg = 255, ctermbg = 239, gui = "NONE", cterm = "NONE" },
	},
	{
		"DiffDelete",
		{ guifg = "white", guibg = "#FF2B2B", ctermfg = 255, ctermbg = 196, gui = "NONE", cterm = "NONE" },
	},
	{
		"DiffText",
		{ guifg = "#000000", guibg = "#ffb733", gui = "NONE", ctermfg = 000, ctermbg = 214, cterm = "NONE" },
	},
	{ "Directory", { guifg = "#A6E22E", gui = "bold" } },
	{ "Error", { guifg = "White", guibg = "Red", ctermfg = 15, ctermbg = 9 } },
	{ "ErrorMsg", { guifg = "White", guibg = "Red", gui = "bold", ctermfg = 15, ctermbg = 1, cterm = "bold" } },
	{ "Exception", { guifg = "#A6E22E", gui = "bold" } },
	{ "Float", { guifg = "#AE81FF" } },
	{ "FoldColumn", { guifg = "#465457", guibg = "#000000", ctermfg = 242, ctermbg = 16 } },
	{ "Folded", { guifg = "#465457", guibg = "NONE", ctermfg = 242, ctermbg = "NONE" } },
	{ "Function", { guifg = "#A6E22E" } },
	{ "Identifier", { guifg = "#FD971F" } },
	{ "Variable", { guifg = "#FD971F" } },
	{ "@variable", { guifg = "#FD971F" } },
	{ "LspInlayHint", { guifg = "#DFCFCF" } },
	{ "Builtin", { guifg = "#FFD180" } },
	{ "Ignore", { guifg = "#808080", guibg = "bg" } },
	{ "Keyword", { guifg = "#F92672", gui = "bold" } },
	{ "Label", { guifg = "#E6DB74", gui = "none" } },
	{ "Macro", { guifg = "#C4BE89", gui = "italic" } },
	{ "SpecialKey", { guifg = "#66D9EF", gui = "italic" } },
	{
		"MatchParen",
		{ guifg = "#000000", guibg = "#FD971F", gui = "NONE", ctermfg = 000, ctermbg = 208, cterm = "NONE" },
	},
	{ "ModeMsg", { guifg = "#E6DB74" } },
	{ "MoreMsg", { guifg = "#E6DB74" } },
	{ "Operator", { guifg = "#F92672" } },
	-- completion/popup menu
	{ "Pmenu", { guifg = "white", guibg = "#000000", ctermfg = 255, ctermbg = 16 } },
	{ "PmenuSel", { guifg = "white", guibg = "#0a9dff", gui = "NONE", ctermfg = 255, ctermbg = 242, cterm = "NONE" } },
	{ "PmenuSbar", { guifg = "NONE", guibg = "#857f78", ctermbg = 232 } },
	{ "PmenuThumb", { guifg = "#242321", guibg = "NONE", ctermfg = 81 } },
	{ "PreCondit", { guifg = "#A6E22E", gui = "bold" } },
	{ "PreProc", { guifg = "#A6E22E" } },
	{ "Question", { guifg = "#66D9EF" } },
	{ "Repeat", { guifg = "#F92672", gui = "bold" } },
	{ "Search", { guifg = "#000000", guibg = "#FFE792", ctermfg = 0, ctermbg = 222, cterm = "NONE" } },
	{ "IncSearch", { guifg = "#C4BE89", guibg = "#000000", ctermfg = 193, ctermbg = 16 } },
	{ "QuickFixLine", { guifg = "NONE", guibg = "#F92672", ctermbg = 197 } },
	-- marks
	{ "SignColumn", { guifg = "#A6E22E", guibg = "#232526" } },
	{ "SpecialChar", { guifg = "#F92672", gui = "bold" } },
	{ "SpecialComment", { guifg = "#7E8E91", gui = "bold" } },
	{ "Special", { guifg = "#66D9EF", guibg = "bg", gui = "italic" } },
	{ "SpellBad", { guisp = "#FF0000", gui = "undercurl", cterm = "underline" } },
	{ "SpellCap", { guisp = "#7070F0", gui = "undercurl", cterm = "undercurl" } },
	{ "SpellLocal", { guisp = "#70F0F0", gui = "undercurl", cterm = "underline" } },
	{ "SpellRare", { guisp = "#FFFFFF", gui = "undercurl", cterm = "underline" } },
	{ "Statement", { guifg = "#F92672", gui = "bold", ctermfg = 197, cterm = "bold" } },
	{ "StatusLine", { guifg = "#455354", guibg = "fg" } },
	{ "StatusLineNC", { guifg = "#808080", guibg = "#080808" } },
	{ "StorageClass", { guifg = "#FD971F", gui = "italic" } },
	{ "Structure", { guifg = "#66D9EF" } },
	{ "Tag", { guifg = "#F92672", gui = "italic" } },
	{ "Title", { guifg = "#ef5939" } },
	{ "Todo", { guifg = "#FFFFFF", guibg = "bg", gui = "bold" } },
	{ "Typedef", { guifg = "#66D9EF" } },
	{ "Type", { guifg = "#66D9EF", gui = "none" } },
	{ "Underlined", { guifg = "#808080", gui = "underline" } },
	{ "VertSplit", { guifg = "#808080", guibg = "#080808", gui = "bold" } },
	{ "VisualNOS", { guifg = "NONE", guibg = "#403D3D" } },
	{ "Visual", { guifg = "NONE", guibg = "#403D3D" } },
	{ "WarningMsg", { guifg = "#FFFFFF", guibg = "#333333", gui = "bold" } },
	{ "WildMenu", { guifg = "#66D9EF", guibg = "#000000" } },
	{ "TabLineFill", { guifg = "#1B1D1E", guibg = "#1B1D1E" } },
	{ "TabLine", { guibg = "#1B1D1E", guifg = "#808080", gui = "none" } },
	{ "Normal", { guifg = "#F8F8F2", guibg = "#1B1D1E" } },
	{ "Comment", { guifg = "#7E8E91" } },
	{ "Cursor", { guifg = "#000000", guibg = "#F8F8F0" } },
}
for _, highlight in ipairs(highlights) do
	local group, props = highlight[1], highlight[2]
	vim.api.nvim_set_hl(0, group, props)
end
